source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'bootstrap-sass', '2.1'
gem 'bcrypt-ruby', '3.0.1'
gem 'will_paginate', '3.0.3'
gem 'bootstrap-will_paginate', '0.0.6'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'uploadify_rails3'
gem 'sqlite3'
# gem "paperclip", '~> 3.4.0'
gem 'faker', '1.0.1'
gem 'jquery-rails'
gem 'jquery-fileupload-rails'
gem 'paperclip'
gem 'bootstrap-sass', '2.1'
gem 'sunspot_rails', '~> 1.3.0'
gem 'sunspot_solr'
gem 'progress_bar'
 gem 'delayed_job_active_record'
gem 'nifty-generators'  
gem 'rails3-jquery-autocomplete'
gem 'rails3-jquery-autocomplete'
gem 'nifty-generators'
gem 'rubyzip'
# gem 'delayed_job_mongoid', '1.0.8'
#gem 'less', '2.2.2' # (at this date)
#gem 'therubyracer'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
gem "cocaine"
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'sunspot_solr'
end
group :test, :development do
  gem 'factory_girl_rails', '4.1.0'
  gem "rspec-rails", "~> 2.0"
  gem 'spork', '>= 0.8.4'
  gem 'capybara', '1.1.2'
  gem 'database_cleaner'
  gem 'pry-debugger'
  gem 'shoulda-matchers', :require => false
  gem 'launchy'
  gem 'better_errors'
  gem 'binding_of_caller'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
