source 'https://rubygems.org'
gem 'rails', '3.2.11'
gem 'sqlite3'

gem 'will_paginate', '3.0.3'
gem 'bootstrap-will_paginate', '0.0.6'
gem 'meta_search'

gem 'metamagic'
gem 'gretel'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem "rspec-rails", ">= 2.12.1", :group => [:development, :test]
gem "database_cleaner", ">= 0.9.1", :group => :test
gem "email_spec", ">= 1.4.0", :group => :test
gem "cucumber-rails", ">= 1.3.0", :group => :test, :require => false
gem "launchy", ">= 2.1.2", :group => :test
gem "capybara", ">= 2.0.2", :group => :test
gem "factory_girl_rails", ">= 4.1.0", :group => [:development, :test]
gem "bootstrap-sass", ">= 2.1.1.0"
#gem 'bootstrap-sass', '2.0.4'
#for use mailchimp
gem "hominid", ">= 3.0.5"
#cho viecc chung thuc nguoi dung mem deo va phan quyen tot
gem "devise", ">= 2.2.0"
gem "cancan", ">= 1.6.8"
gem "rolify", ">= 3.2.0"
gem "simple_form", ">= 2.0.4"
gem "google_visualr", ">= 2.1.2"
gem "jquery-datatables-rails", ">= 1.11.2"
gem "quiet_assets", ">= 1.0.1", :group => :development

group :development, :test do
  gem 'guard-rspec', '1.2.1'
  gem 'guard-spork', '1.2.0'
  gem 'spork', '0.9.2'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-stack_explorer'
  gem 'pry-debugger'
end
